rvm:
    - 2.3.1

cache: bundler

before_script:
    - npm install -g phantomjs-prebuilt
    - bundle exec rake db:migrate RAILS_ENV=test

after_script:
  - bundle exec codeclimate-test-reporter

addons:
    firefox: "49.0"
    code_climate:
        repo_token: f50babd465bb9c116e6bbda18a37eb257d2d1db2baa40b3e9096cd5c2b798fa7
